version: 2.15

before:
  hooks:
    - go mod download
    - go vet ./...

builds:
  - id: linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./main.go
    ldflags: "-X github.com/libost/sticker_go/version.Version={{ if eq .Env.RELEASE_CHANNEL \"dev\" }}{{ .ShortCommit }}{{ else }}{{ .Version }}{{ end }} -X github.com/libost/sticker_go/version.BuildTime={{.Date}} -X github.com/libost/sticker_go/version.GitCommit={{.ShortCommit}} -X github.com/libost/sticker_go/version.Branch={{.Branch}}"
    binary: sticker_go

  - id: windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    main: ./main.go
    ldflags: "-X github.com/libost/sticker_go/version.Version={{ if eq .Env.RELEASE_CHANNEL \"dev\" }}{{ .ShortCommit }}{{ else }}{{ .Version }}{{ end }} -X github.com/libost/sticker_go/version.BuildTime={{.Date}} -X github.com/libost/sticker_go/version.GitCommit={{.ShortCommit}} -X github.com/libost/sticker_go/version.Branch={{.Branch}}"
    binary: sticker_go

  - id: macos
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./main.go
    ldflags: "-X github.com/libost/sticker_go/version.Version={{ if eq .Env.RELEASE_CHANNEL \"dev\" }}{{ .ShortCommit }}{{ else }}{{ .Version }}{{ end }} -X github.com/libost/sticker_go/version.BuildTime={{.Date}} -X github.com/libost/sticker_go/version.GitCommit={{.ShortCommit}} -X github.com/libost/sticker_go/version.Branch={{.Branch}}"
    binary: sticker_go

archives:
  - id: binaries
    formats: [binary]
    ids:
      - linux
      - windows
      - macos

checksum:
  name_template: checksums.txt

nfpms:
  - id: "sticker_go"
    maintainer: "libost"
    vendor: "libost"
    description: "A Telegram sticker conversion bot written in Go."
    license: "MIT"
    file_name_template: "sticker_go_{{.Version}}_{{.Os}}_{{.Arch}}.deb"
    formats:
      - deb
    contents:
      - src: ./env.config.yaml
        dst: /etc/sticker_go/config.yaml

release:
  prerelease: auto
  target_commitish: "{{ .Commit }}"
  mode: replace

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Maintenance
      regexp: '^.*?(chore|docs|style|refactor|perf|test)(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - '^Merge pull request #\d+ from .+$'
      - '^Merge branch .+$'

announce:
  telegram:
    enabled: true
    chat_id: "@submit_bot_testing"
    message_template: "New release: {{ .Tag }}\n\n{{ .ReleaseNotes }}\n\nDownload: {{ .ReleaseURL }}"
    parse_mode: MarkdownV2