version: "3.8"

services:
  sticker_go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sticker_go
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
