CREATE TABLE IF NOT EXISTS USERPOOL (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at BIGINT NOT NULL DEFAULT 0,
    user_id BIGINT NOT NULL UNIQUE,
    obfu_id VARCHAR(128) NOT NULL UNIQUE,
    last_cycle_starts_at BIGINT NOT NULL DEFAULT 0,
    usage_count BIGINT NOT NULL DEFAULT 0,
    total_usage_count BIGINT NOT NULL DEFAULT 0,
    user_group VARCHAR(32) NOT NULL DEFAULT 'user',
    language_code VARCHAR(32) NULL,
    timezone VARCHAR(64) NULL
);

CREATE TABLE IF NOT EXISTS GRACE_KEY (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    generated_at BIGINT NOT NULL DEFAULT 0,
    operator BIGINT NOT NULL,
    expires_at BIGINT NOT NULL DEFAULT 0,
    uuid VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS DONATION_LOGS (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    timestamp BIGINT NOT NULL DEFAULT 0,
    user_id BIGINT NOT NULL,
    amount BIGINT NOT NULL,
    payload VARCHAR(255) NOT NULL UNIQUE,
    telegram_payment_charge_id VARCHAR(255) NOT NULL,
    provider_payment_charge_id VARCHAR(255) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'pending'
);

CREATE TABLE IF NOT EXISTS STATISTICS (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    weekday VARCHAR(16) NOT NULL UNIQUE,
    daily_usage_count BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS LAST_CLEANUP (
    id BIGINT NOT NULL PRIMARY KEY,
    last_cleanup_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS PERSISTENT_DATA (
    id BIGINT NOT NULL PRIMARY KEY,
    last_api_endpoint TEXT,
    last_api_token TEXT
);