# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "dev", "dev_tgs" ]
    paths-ignore:
      - ".github/**"
      - ".github/workflows/**"
      - "config.yaml"
      - "**.md"
      - ".gitignore"
      - "LICENSE"
      - "docs/**"
      - "examples/**"
      - "scripts/**"
  pull_request:
    branches: [ "dev" ]
    paths-ignore:
      - ".github/**"
      - ".github/workflows/**"
      - "config.yaml"
      - "**.md"
      - ".gitignore"
      - "LICENSE"
      - "docs/**"
      - "examples/**"
      - "scripts/**"

jobs:
  build:
    name: Build on ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}  # 告诉 GitHub 分别开这几台机器
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: sticker_go
            suffix: ""
          - os: windows-latest
            artifact_name: sticker_go
            suffix: ".exe"
          - os: macos-latest
            artifact_name: sticker_go
            suffix: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Prepare version info
        id: meta
        shell: bash
        run: |
          # 获取当前时间并格式化为字符串
          echo "build_time=$(date +'%Y-%m-%d_%T')" >> $GITHUB_OUTPUT
          # 获取短 Commit ID (前 7 位)
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          # 获取分支名
          echo "branch=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Build
        shell: bash
        run: go build -ldflags "-X libost/sticker_go/version.Version=${{ github.ref_name }} -X libost/sticker_go/version.BuildTime=${{ steps.meta.outputs.build_time }} -X libost/sticker_go/version.GitCommit=${{ steps.meta.outputs.short_sha }} -X libost/sticker_go/version.Branch=${{ steps.meta.outputs.branch }}" -v -o sticker_go-${{ matrix.os}}${{ matrix.suffix }}  # 这里换成你语言的编译命令

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}-${{ matrix.os }}  # 把不同平台的文件分别保存
          path: sticker_go*